name: test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'LICENSE*'
      - 'README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'LICENSE*'
      - 'README.md'

jobs:

  test-compat:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.7.17'
    - run: python tests/test.py

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.14.2'
    - run: python tests/test.py
